on:
  push:
    branches:
      - dev
      - main
  pull_request:

name: Assess Code Quality

jobs:
  code-quality:
    name: code-quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@master

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: clippy, rustfmt

      - name: Formatting check
        run: cargo +nightly fmt --all -- --check

      - name: Linting check
        env:
          RUSTFLAGS: -Awarnings # ignore warnings for clippy
        run: cargo clippy --all-targets
